accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

	path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
	path('signup/',views.SignUp.as_view(),name='signup'),
	path('logout/',auth_views.LogoutView.as_view(),name='logout')

]

datasets/urls.py
from django.urls import path


from . import views
app_name = 'datasets'

urlpatterns = [

	path('login_first/',views.Not_logged_in.as_view(),name='login_first'),
	path('list/', views.DataSetsList.as_view(),name='list'),
	path('dataset/<int:pk>/',views.DatasetDetailView.as_view(),name='detail'),
	path('create/',views.CreateDatasetView.as_view(), name='create'),
	path('update/<int:pk>/',views.UpdateDatasetView.as_view(),name='update'),
	path('choose_new_dataset/',views.ChooseNewDataset.as_view(),name='choose_new_dataset'),
	path('categorical_columns/', views.DataSetCategoricalColumns.as_view(),name='categorical_columns'),
	path('regression_or_classification/',views.ClassificationOrRegression.as_view(),name='classification_or_regression'),
	path('neural_network_graph_and_keras_model/',views.NeuralNetworkDiagramAndKerasModel.as_view(),name='neural_network_graph_and_keras_model'),
	path('numberical_columns/',views.DataSetNumericalColumns.as_view(),name='numerical_columns'),
	path('label_column/',views.DataSetLabelColumn.as_view(),name='label_column'),
	path('show_selected_columns/',views.ShowSelectedColumns.as_view(),name='show_selected_columns'),
	path('select_dataset_for_training/',views.SelectDataSet.as_view(),name='select_dataset_for_training'),
	path('select_model_type/',views.SelectModelType.as_view(),name='select_model_type')


	
]

machine_learning_gui/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('welcome/', views.Welcome.as_view(),name='welcome'),
    path('thanks/',views.ThankYou.as_view(),name='thanks'),
    path('accounts/',include('accounts.urls')),
    path('datasets/',include('datasets.urls')),
]

datasets/forms.py
from django import  forms
import os
from django.db.models.fields.files import FieldFile
from pandas import read_html
import pandas as pd
from .models import DataSets
from machine_learning_gui import settings
import requests

class Base():

	def raise_error(self):

		raise NotImplementedError('IT must be inherited')

class NotCsvFile(Base):

	def raise_error(self):

		raise forms.ValidationError('The file must be a csv file')

class AllFieldsFilled(Base):

	def raise_error(self):
		raise forms.ValidationError("Only one of the fields needs to be filled")

class AllFieldsEmpty(Base):

	def raise_error(self):

		raise forms.ValidationError("One of the fields  needs to be filled")

class FileNotUnique(Base):

	def raise_error(self):

		raise forms.ValidationError("A dataset with that file already exists")

class UrlNotUnique(Base):

	def raise_error(self):

		raise forms.ValidationError("A data set with that link already exists")

class RunOutOfSpace(Base):

	def raise_error(self):

		raise forms.ValidationError('You run out of space! go to the DataSets page and replace one')

class NoTablesFound(Base):

	def raise_error(self):

		raise forms.ValidationError('The website you provided does not have any tables')


class InvalidCsvFile(Base):
	def raise_error(self):

		raise forms.ValidationError('The file you provided is invalid')

def raise_error_message(obj):

	obj.raise_error()

class DataSetsForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		self.username = kwargs.pop('username',None)
		self.update_view_running = kwargs.pop('update_view_running',None)
		self.pk = kwargs.pop('pk',None)
		self.previous_file_cleared = kwargs.pop('clear_previous_file',None)  # get value of the clear file checkbox in update view
		self.saved_to_session_instead = kwargs.pop('saved_to_session_instead',None)
		super().__init__(*args, **kwargs)

	class Meta():

		model = DataSets

		fields = ('file','link')

	def more_than_10_datasets_found(self):

		 return DataSets.objects.filter(user__username__iexact=self.username).count() == 10 and not self.update_view_running # datasets can still be saved in update view

	def save_updated_data(self,file,url):

		current_dataset = DataSets.objects.get(pk=self.pk)  
		current_dataset.file = file
		current_dataset.link = url
		current_dataset.save()

	def file_exists(self,file): # returns if the chosen file is already taken

		'''
		when updating a dataset that had a file, if the previous file is not updated, the file-field input will return 'datasets/file-name', but if its updated it 
		will return 'file-name'. so there is no need to check if the file is a new one or a saved one.

		'''
		if not self.saved_to_session_instead: # if the person chose an existing dataset instead of a new one (if you chose a new dataset, the file/link does not have to be unique)
			base_dir = settings.media_dir
			saved_file_name = ''.join(map(lambda x: '' if x in ['(',')'] else x,str(file))).replace(' ','_') # removes () and replaces spaces with _, this is how django saves files
			file_path  = os.path.join('datasets',self.username+saved_file_name)
			full_path = os.path.join(base_dir,str(file_path))
			return  os.path.isfile(full_path) 


	def url_exists(self,url):

		return  not self.saved_to_session_instead and url and DataSets.objects.filter(user__username__iexact=self.username,link=url).exclude(pk=self.pk).exists() ## the 'exclude' is there if the user edits a dataset but does not make any changes, and saves it
		
	def no_tables_found(self,url):

		try:

			pd.read_html(requests.get(url).text)
		except:

			return True


	def clear_file_checkbox(self,cleaned_data): 

		'''
			implements django's clear file checkbox functionality. this functionality is implemented because when posting,
			ajax is used, and also form.PreventDefault() is used.
		'''
		
		if self.update_view_running:  # the checkbox is only in the update view

			is_checkbox_checked = eval(self.previous_file_cleared.capitalize())# since its gotten from a javascript POST the first letter of the bool will not be capitalized and its also of type <str>. converts 'false/true' to False/True
			current_file = cleaned_data.get('file')
			if is_checkbox_checked and  isinstance(current_file, FieldFile):  # if the current file is the  one saved in the model and the clear checkbox is clicked. clear it
				cleaned_data['file'] = None		

		return cleaned_data


	def file_is_csv(self,file):
		return str(file).endswith('.csv')
	def csv_file_valid(self,file):
		
		
		try:
			pd.read_csv(file)
			return True
		except:
			return False
		

	def clean(self):

		self.cleaned_data = self.clear_file_checkbox(self.cleaned_data)  # remove the saved file if the checbox is checked off
		url = self.cleaned_data.get('link')
		file = self.cleaned_data.get('file')
		possible_errors = { 'RunOutOfSpace()':self.more_than_10_datasets_found(),
							'AllFieldsEmpty()': not url and not file,
							'AllFieldsFilled()': url and file ,
							'FileNotUnique()': self.file_exists(file),
							'UrlNotUnique()':  self.url_exists(url),
							'NoTablesFound()': url and self.no_tables_found(url),
							'NotCsvFile()':   file and not self.file_is_csv(file),
							"InvalidCsvFile()": file and not self.csv_file_valid(file)
		}

		for obj,error in possible_errors.items():
			if error:
				
				object = eval(obj)

				raise_error_message(object)

		
		if self.update_view_running:
			self.save_updated_data(file,url)  # i did the saving here because if i did it in the update view it would override the functionality of the clear checkbox

datasets/views.py
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from .forms import DataSetsForm
from django.contrib.auth.mixins import LoginRequiredMixin
import requests
from machine_learning_gui import settings
from urllib.parse import unquote
import pandas as pd
from . import models
from django.views import  generic
import os
from django.core.validators import URLValidator
from django.shortcuts import render



def dataset_saved_in_session(request):

	return request.COOKIES['dataset_location'] == '' and request.COOKIES['primary_key'] == ''

def dataset_location_is_url(dataset_location):
	
	url_validator = URLValidator()

	try:
		return url_validator(dataset_location) == None # it returns none if its a valid url
	except:
		return False

def filtered_data_frame(request,dataframe):
	selected_columns  = unquote(request.COOKIES['categorical_columns']).split(',') + unquote(request.COOKIES['numerical_columns']).split(',') + [unquote(request.COOKIES['label_column'])]
	selected_columns = list(filter(None,selected_columns))  # if there are no categorical or numerical remove the epmpty spaces
	dataframe = dataframe[selected_columns]
	return dataframe

def get_dataframe_given_url_or_file(dataframe_location):

	if dataset_location_is_url(dataframe_location):

			dataframe = remove_column(pd.read_html(requests.get(dataframe_location).text)[0]) 
	else:
			dataframe = pd.read_csv(dataframe_location)

	return dataframe

def get_dataframe(request):

		if dataset_saved_in_session(request):

			dataset_location = unquote(request.session['dataset_location'])# its encoded in percents
			dataframe  = get_dataframe_given_url_or_file(dataset_location)
		else:  

			dataset_location = unquote(request.COOKIES['dataset_location'])  # its encoded in percents		
			dataframe  = get_dataframe_given_url_or_file(dataset_location)

		return dataframe.columns,dataframe


def remove_column(dataframe):

	'''

	when scrapping dataframes from pages, panda's read_html() adds a 'unnamed' column that has a buch of nans. this 
	method removes that

	'''
	try:
		return dataframe.drop('Unnamed: 0',axis=1)
	except:
		return dataframe
	
def return_customized_dataframe(dataframe,categorical_columns):
	'''
		drop rows that have missing cells, and onehot encode the categorical columns
	'''
	categorical_columns = list(filter(None,categorical_columns))  # return an empty list if there are no categorical columns. i.e  [''] = [] or ['','some categorical column'] = ['some categorical column']
	dataframe = dataframe.dropna()
	dataframe = pd.get_dummies(data = dataframe, columns =categorical_columns,drop_first=True) if categorical_columns else dataframe
	return dataframe
class Not_logged_in(generic.TemplateView):

	template_name = 'datasets/not_logged_in.html'

class ClassificationOrRegression(generic.TemplateView):
	template_name = 'datasets/regression_or_classification.html'


class DataSetsList(LoginRequiredMixin,generic.ListView):

	model = models.DataSets
	context_object_name = 'datasets'
	login_url = 'datasets:login_first'

	def get_queryset(self):
		return self.model.objects.filter(user__username = self.request.user.username)

class DatasetDetailView(LoginRequiredMixin,generic.DetailView):


	template_name = 'datasets/datasets_detail.html'
	model = models.DataSets

	login_url = 'datasets:login_first'

	def get_context_data(self, **kwargs):
		dataframe,num_rows,num_nans = self.get_object()
		return {
			"DataFrame": dataframe,
			'dataset':  get_object_or_404(self.model, pk=self.kwargs.get('pk')),
			'num_rows':num_rows,
			'num_nans':num_nans

		}

	def get_object(self):
      
			data = get_object_or_404(self.model, pk=self.kwargs.get('pk'))

			if data.link:
				dataframe = remove_column(pd.read_html(requests.get(data.link).text)[0])

			elif data.file:
				dataframe= pd.read_csv(data.file.path)

			return dataframe.head(),dataframe.shape[0],len(dataframe)-len(dataframe.dropna())

		
class CreateDatasetView(LoginRequiredMixin,generic.CreateView):

	form_class = DataSetsForm
	template_name = 'datasets/create.html'
	login_url = 'datasets:login_first'
	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.user = self.request.user
		self.object.file = self.request.FILES.get('file')
		self.object.save()
		return redirect('datasets:detail', pk=self.object.pk)					
	def get_form_kwargs(self): ## used to pass in the 'username' argument to the forms.py file

			kwargs = super(CreateDatasetView, self).get_form_kwargs()
			kwargs.update({

				'username': self.request.user.username,

				})
			
			return kwargs 
			

class UpdateDatasetView(LoginRequiredMixin,generic.UpdateView):



	model = models.DataSets

	form_class = DataSetsForm
	template_name = 'datasets/update.html'

	context_object_name = 'form'
	login_url = 'datasets:login_first'
	def get_context_data(self, **kwargs):

		context = super().get_context_data(**kwargs)
		context['id'] = self.kwargs.get('pk')

		return context

	def get_form_kwargs(self):
			kwargs = super(UpdateDatasetView, self).get_form_kwargs()
			kwargs.update({

				'update_view_running': True,
				'username':self.request.user.username,
				'pk':self.kwargs.get('pk'),
				'clear_previous_file':self.request.POST.get('clear-previous-file') # value of the clear file checkbox

				})
			
			return kwargs 
	
	def form_valid(self, form):
		
		return redirect('home')


class ChooseNewDataset(generic.CreateView):
	'''
		if the user wants to select a new dataset instead of choosing one from their account
	'''
	form_class = DataSetsForm
	template_name = 'datasets/choose_new_dataset.html'

	def form_valid(self, form):

		self.object = form.save(commit=False)

		if not self.request.session or not self.request.session.session_key:
			self.request.session.save()


		if self.object.file:
			temparory_location = os.path.join(settings.MEDIA_ROOT,'datasets/temp_file.csv')
			with open(temparory_location ,'wb+') as f:
				for chunk in self.request.FILES['file'].chunks():
					f.write(chunk)
			self.request.session['dataset_location'] = temparory_location
		else:
			self.request.session['dataset_location'] = self.object.link

		return redirect('datasets:list')

	def get_form_kwargs(self):
			kwargs = super(ChooseNewDataset, self).get_form_kwargs()
			kwargs.update({

				'saved_to_session_instead':True

				})
			
			return kwargs 

class DataSetCategoricalColumns(generic.TemplateView):

	'''
		choose/select the categorical columns of the dataset
	'''
	template_name = 'datasets/categorical_columns.html'

	

	def get_context_data(self, **kwargs):  

		context = super().get_context_data(**kwargs)
		numerical_columns = unquote(self.request.COOKIES['numerical_columns'])
		context['dataframe_columns'] = get_dataframe(self.request)[0] 
		context['dataframe'] = get_dataframe(self.request)[1]
		context['numerical_columns'] = numerical_columns  # used to higlight them in the grid

		return context

class DataSetNumericalColumns(generic.TemplateView):
	'''
		select numerical columns of the dataset
	'''
	template_name = 'datasets/numerical_columns.html'

	def get_context_data(self, **kwargs):

		context = super().get_context_data(**kwargs) 
		context['dataframe_columns'] = get_dataframe(self.request)[0]  # it get_dataframe() returns the dataframe columns and the dataframe
		context['dataframe'] = get_dataframe(self.request)[1]
		context['label_column'] = unquote(self.request.COOKIES['label_column'])

		return context

class DataSetLabelColumn(generic.TemplateView):
	'''
		select the label column of the dataset
	'''
	template_name = 'datasets/label_column.html'
	def get_context_data(self, **kwargs):

		context = super().get_context_data(**kwargs)
		context['dataframe_columns'] = get_dataframe(self.request)[0]
		context['dataframe'] = get_dataframe(self.request)[1]
		context['num_of_rows'] = len(context['dataframe'].dropna()) # used later to set the max batch size
		return context

class ShowSelectedColumns(generic.TemplateView):

	'''
		in the training page, show the column types (what numerical columns were selected,what categorical columns were selected,
		what is the label column, and what columns were not selected)
	'''
	template_name = 'datasets/show_selected_columns.html'
	def get_context_data(self, **kwargs):

		context = super().get_context_data(**kwargs)
		numerical_columns = unquote(self.request.COOKIES['numerical_columns'])
		categorical_columns = unquote(self.request.COOKIES['categorical_columns'])
		context['dataframe_columns'] = get_dataframe(self.request)[0] 
		context['dataframe'] = get_dataframe(self.request)[1].head(10)
		context['numerical_columns'] = numerical_columns  # used to higlight them in the grid
		context['categorical_columns'] = categorical_columns


		return context
class NeuralNetworkDiagramAndKerasModel(generic.TemplateView):  

	'''
		this is the page where the neural network is built and trained
	'''
	template_name = 'datasets/neural_network.html'
	def get_context_data(self, **kwargs):

		# all this method is needed for is access to the session and cookies (nothing is added to the context dict)
		context = super().get_context_data(**kwargs)
		media_path = os.path.join(settings.MEDIA_ROOT,'datasets/')
		dataframe  = get_dataframe_given_url_or_file(unquote(self.request.COOKIES['dataset_location'])) if not dataset_saved_in_session(self.request) else get_dataframe_given_url_or_file(unquote(self.request.session['dataset_location']))
		dataframe = filtered_data_frame(self.request,dataframe)  # only return the selected columns
		categorical_columns = unquote(self.request.COOKIES['categorical_columns']).split(',')
		dataframe = return_customized_dataframe(dataframe,categorical_columns) # remove nans and onehot encode categorical columns
		dataframe.to_csv(os.path.join(media_path,self.request.COOKIES['sessionid']+'formated_dataset.csv'))

		return context

class SelectDataSet(generic.TemplateView):
	template_name = 'datasets/select_dataset_for_training.html'

datasets/templates/datasets/categorical_columns.html
{% extends "datasets/base_dataset.html" %}
{% load filter %}
{% load static %}
{% load filter %}


{% block css_style %}
	<link rel="stylesheet" type="text/css" href="{% static 'datasets/css/grid.css' %}">
	<style type="text/css">
		
		body{
			text-align: center
		}
	</style>
{% endblock %}


{% block content %}
	<button id='can_continue' type="button" class="btn btn-primary" style='position:fixed;left:43%;'><h1 style='color:yellow'>Continue</h1></button><br><br><br>
{% if request.COOKIES.label_is == 'discrete' %}
	<h1>Classification</h1>
	{% else %}
	<h1>Regression</h1>
{% endif %}
<h1>Select The Categorical Columns</h1>

	
<div class = 'grid-container'>
	
	{% for column in dataframe_columns %}
		
		{% if column in numerical_columns %}
			<div class='grid-item numerical_columns' align='center' style='background-color:green'>
				
				<h4><em>Numerical Column</em></h4>
				<hr>
				<h3>{{column}}</h3>
				
				<h4>{{dataframe|get_data_in_column:column|safe}} </h4>
			</div>
			{% elif  request.COOKIES.label_column  == column %}
				<div class='grid-item label_column' style='background-color:yellow' align='center'>
					<h4> <em>Label Column</em></h4>
					<hr>
					<h3>{{column}}</h3>
					<h4>{{dataframe|get_data_in_column:column|safe}} </h4>
					
				</div>
				
			{% else %}
				<div id='{{column}}' class='grid-item' align='center'>
					<h3>{{column}}</h3>
					<h4>{{dataframe|get_data_in_column:column|safe}} </h4>
				</div>
			{% endif %}
			
		{% endfor %}
	</div>
{% endblock content %}

{% block scripts %}
	<script type="text/javascript">
		$('.grid-item').not('.numerical_columns').not('.label_column').click(function(){
			
			$(this).toggleClass("higlight_selected");
			
		});


		$('#can_continue').click(function(){

			var categorical_columns = $('.higlight_selected');
			var categorical_column_names = [];
			for(var i = 0; i < categorical_columns.length;i++){
				categorical_column_names.push($(categorical_columns[i]).attr('id'))
			}
			
			Cookies.set('categorical_columns',categorical_column_names,{path:'/'})
			
			window.location  = '{% url "datasets:select_model_type" %}'
			


		});
		
	</script>
{% endblock scripts %}

	

datasets/templates/datasets/current_dataset.html
	

{{dataframe.to_html|safe}}

datasets/templates/datasets/datasets_list.html
{% extends "datasets/base_dataset.html" %}
{% load static %}

{% block content %}

		<link rel="stylesheet" type="text/css" href="{% static 'datasets/css/grid.css' %}">	
		<link rel="stylesheet" type="text/css" href="{% static 'datasets/css/shift_colors_scroll_down_icon.css' %}">
		<div class="grid-container">
		  {% for dataset in datasets  %}

		 	<div class="grid-item">

		 		<p>{{dataset.title|safe}}</p><br>
		 		

		 		<a href="{% url 'datasets:update' pk=dataset.pk %}" data-toggle="modal" data-target="#modal-update"><i title='Update' class="far fa-edit icon-2x fa-2x"></i></a>
		 		<br>

		 		<a class='view' id='{{dataset.pk}}' title='View' data-toggle='modal' data-target='#dataframe'><i class="fas fa-eye fa-4x"></i></a>

		 		

		 	</div>

		 	{% endfor %}

		 	{% if  not datasets.count == 10 %}


		 	<a id='create' class='grid-item' title='add a new dataset' class='nav-link' href="{% url 'datasets:create' %}" data-toggle="modal" data-target="#modal"><i style='position:relative;top:38%' class="fas fa-plus-circle fa-5x"></i></a>

		 		{% endif %}
		  
		</div>
		<i class="fas fa-arrow-circle-right fa-4x scroll_button"></i>


			

<script type="text/javascript" src='{% static "datasets/js/scroll_right.js" %}'></script>
<script type="text/javascript" src='{% static "datasets/js/populate_popup_detail_view.js" %}'></script>
{% endblock content %} 

datasets/templates/datasets/label_column.html
{% extends "datasets/base_dataset.html" %}
{% load filter %}
{% load static %}

{% block css_style %}
	<link rel="stylesheet" type="text/css" href="{% static 'datasets/css/grid.css' %}">
	<style type="text/css">
		
		body{
			text-align:center;
		}
	</style>
{% endblock css_style %}

{% block content %}
	<p id = 'num_of_rows' style='display:none'>{{num_of_rows}}</p>
	<button id='can_continue' type="button" class="btn btn-primary" style='position:fixed;margin-left:44%;display:none'><h1 style='color:yellow'>Continue</h1></button><br><br><br>
{% if request.COOKIES.label_is == 'discrete' %}
	<h1>Classification</h1>
	{% else %}
	<h1>Regression</h1>
{% endif %}
<h1>Select The Label Column</h1>

<div class = 'grid-container'>
	
	{% for column in dataframe_columns %}
		<div class='grid-item' align='center' id='{{column}}'>
			{% if request.COOKIES.label_is == 'continuous' and dataframe|is_numerical:column %}
				<div>

					<p>Contains Only Numbers</p>
				</div>
			{% endif %}
			<h3>{{column}}</h3>
			<h4>{{dataframe|get_data_in_column:column|safe}} </h4>
			
		</div>
		
		
	{% endfor %}

</div>
{% endblock content %}

{% block scripts %}
	<script type="text/javascript">


	$('.grid-item').click(function(){
		// if the column selected is numerical and regression is being done, or if classification is being done (only numerical columns can be labels for regression)
		if($(this).find('div').length==1 && Cookies.get('label_is') == 'continuous' || Cookies.get('label_is') != 'continuous' ){

			$('.grid-item').removeClass('higlight_selected'); // unselect the previous label column															
			$(this).addClass("higlight_selected");  // select the curent label column
			$('#can_continue').css('display','block'); // remove the continue button
			
		}

		// if its regression and the user selected a column that is not numerical, alert them
		else if($(this).find('div').length!=1 && Cookies.get('label_is') == 'continuous'){
			alert('this column contains strings');
		};

		
	});

	
	$('#can_continue').click(function(){

			var column_name = $('.higlight_selected').attr('id')
			Cookies.set('num_of_rows',$('#num_of_rows').text(),{path:'/'}) 
			Cookies.set('label_column',column_name,{path:'/'});
			$('.ajax_part_of_page').html('<div align="center"><img src="https://theplaycave.com.au/wp-content/uploads/2016/10/loading.gif"></div>')
			window.location = '{% url "datasets:numerical_columns" %}'

		});
	
</script>
{% endblock scripts %}

datasets/templates/datasets/not_logged_in.html
{# {% extends "datasets/base_dataset.html" %} #}
{% load static %}


{% block content %}

<h1>You must Log in First</h1>
	
{% endblock content %}

datasets/templates/datasets/regression_or_classification.html
{% extends "datasets/base_dataset.html" %}
{% load static %}
{% block css_style %}
	<link rel="stylesheet" type="text/css" href="{% static 'datasets/css/grid.css' %}">
	<style type="text/css">
		button{
			background-color: #4d0000
		}
	</style>
{% endblock css_style %}
{% block content %}
	<div class='grid-container'  style='margin-left:35%'>
		<button id='classification' class='grid-item'><h1>Classification</h1></button>
		<button id='regression' class='grid-item'><h1>Regression</h1></button>
	</div>
{% endblock content %}

{% block scripts %}
	
	<script type="text/javascript">

		$('#classification').on('click',function(){

			Cookies.set('label_is','discrete',{path:'/'}) 
			window.location = '{% url "datasets:label_column" %}'
				

		});


		$('#regression').on('click',function(){

			Cookies.set('label_is','continuous',{path:'/'}) 
			window.location = '{% url "datasets:label_column" %}'
				
		});

	</script>


{% endblock scripts %}

datasets/templates/datasets/select_dataset_for_training.html
{% extends "datasets/base_dataset.html" %}
{% load static %}
{% block css_style %}
	<link rel="stylesheet" type="text/css" href="{% static 'datasets/css/grid.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'datasets/css/shift_colors_scroll_down_icon.css' %}">
	<style type="text/css">
		
	</style>
{% endblock css_style %}
{% block content %}

	<h1 align="center">Select a dataset for training</h1>
	<div style='text-align:center;height:100%;overflow:scroll;'>
		
		
		
		<button id='can_continue' type="button" class="submit-btn btn btn-primary" style='display:none;position:fixed;left:45%'><h1 style='color:yellow'>Continue</h1></button>
		<div class="grid-container" align=center>
			<a style='background-color:green;' id='create' class='grid-item' title='add a new dataset' class='nav-link' href="{% url 'datasets:choose_new_dataset' %}" data-toggle="modal" data-target="#modal"><h1>New DataSet</h1><br>
				<i class="fas fa-plus-circle fa-5x"></i>
			</a>
			{% if user.is_authenticated and user.datasets.count > 0 %}
				{% for dataset in user.datasets.all  %}
					{% include "datasets/_datasets_selectable_list.html" %}
					
					
				{% endfor %}
			{% endif %}
		</div>
		<i class="fas fa-arrow-circle-right fa-4x fa-pulse scroll_button"></i>
{% endblock content %}

{% block scripts %}
	<script type="text/javascript" src='{% static "datasets/js/populate_popup_detail_view.js" %}'></script>
	<script type="text/javascript" src='{% static "datasets/js/scroll_right.js" %}'></script>
	<script type="text/javascript">


		// handle the selecting of datasets by adding a class to the clicked dataset.
		$('.grid-item').not('#create').click(function(){
			$('#can_continue').css('display','block'); // show the continue button only after a dataset has be selected
			$('.grid-item').removeClass('higlight_selected'); // unselect the previous dataset
			console.log($(this))
			$(this).addClass("higlight_selected"); // select the current dataset		
		});

		$('#can_continue').click(function(){

				var selected_dataset = $('.higlight_selected');
				let num_of_rows = $(selected_dataset).find('#num_of_rows').text()
				$('#can_continue').remove(); // remove continue button
				var current_dataset_location = $(selected_dataset).find('#dataset_location').text(); // '#dataset_location' is the id of a paragraph in the _datasets_selectable_list.html that contains the path/url of the selected dataset
				var current_dataset_pk = $(selected_dataset).find('.view').attr('id'); //  the id of the view button on each dataset contains the primary key of the dataset

				// set cookies 
				// Cookies.set('num_of_rows',num_of_rows,{path:'/'})
				Cookies.set('primary_key',current_dataset_pk,{path:'/'});
				Cookies.set('dataset_location', current_dataset_location, {path: '/' });
			
				window.location = '{% url "datasets:classification_or_regression" %}'
		});


	</script>
	
{% endblock scripts %}