accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

	path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
	path('signup/',views.SignUp.as_view(),name='signup'),
	path('logout/',auth_views.LogoutView.as_view(),name='logout')

]

datasets/urls.py
from django.urls import path


from . import views
app_name = 'datasets'

urlpatterns = [

	path('login_first/',views.Not_logged_in.as_view(),name='login_first'),
	path('list/', views.DataSetsList.as_view(),name='list'),
	path('dataset/<int:pk>/',views.DatasetDetailView.as_view(),name='detail'),
	path('create/',views.CreateDatasetView.as_view(), name='create'),
	path('update/<int:pk>/',views.UpdateDatasetView.as_view(),name='update'),
	path('choose_new_dataset/',views.ChooseNewDataset.as_view(),name='choose_new_dataset'),
	path('categorical_columns/', views.DataSetCategoricalColumns.as_view(),name='categorical_columns'),
	path('regression_or_classification/',views.ClassificationOrRegression.as_view(),name='classification_or_regression'),
	path('neural_network_graph_and_keras_model/',views.NeuralNetworkDiagramAndKerasModel.as_view(),name='neural_network_graph_and_keras_model'),
	path('numberical_columns/',views.DataSetNumericalColumns.as_view(),name='numerical_columns'),
	path('label_column/',views.DataSetLabelColumn.as_view(),name='label_column'),
	path('show_selected_columns/',views.ShowSelectedColumns.as_view(),name='show_selected_columns'),
	path('select_dataset_for_training/',views.SelectDataSet.as_view(),name='select_dataset_for_training'),
	path('select_model_type/',views.SelectModelType.as_view(),name='select_model_type')


	
]

machine_learning_gui/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('welcome/', views.Welcome.as_view(),name='welcome'),
    path('thanks/',views.ThankYou.as_view(),name='thanks'),
    path('accounts/',include('accounts.urls')),
    path('datasets/',include('datasets.urls')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% block body_block %}
  <html>
    <head>
      <title></title>

      <script type="text/javascript" src='https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js'></script>
        <script src="{% static 'datasets/js/cookie.js' %}"></script>
      <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>
      <script src="https://kit.fontawesome.com/dac342a98d.js" crossorigin="anonymous"></script>
      {% block css_style %}
        
      {% endblock css_style %}
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'datasets:list' %}">DataSets</a>
              </li>
             
               <li  class="nav-item">
                <a title='add a new dataset' class='nav-link' href="{% url 'datasets:create' %}" data-toggle="modal" data-target="#modal">New Dataset</i></a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
              </li>

             
            {% else %}
              <li class="nav-item">
                <a id='open-login-popup' class="nav-link" href="{% url 'accounts:login' %}" data-toggle='modal' data-target='#login'>LogIn</a>
              </li>
              <li  class="nav-item mr-right">
                <a class="nav-link" href="{% url 'accounts:signup' %}" data-toggle='modal' data-target = '#signup-modal'>SingUp</a>
              </li>
              
            {% endif %}
            
                   
          </ul>
            <a class="nav-link" href="https://github.com/mraa022/machine_learning_GUI_app"><i class="fab fa-github fa-2x"></i></a>
        </div>
      </nav>
      <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
          <div class="modal-content"></div>
        </div>
      </div>

      <div class="modal fade" tabindex="-1" role="dialog" id="modal-update">
        <div class="modal-dialog" role="document">
          <div class="modal-content"></div>
        </div>
      </div>

      <div class="modal fade" tabindex="-1" role="dialog" id="dataframe">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content"></div>
        </div>
      </div>

      <div class="modal fade" tabindex="-1" role="dialog" id="login">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content"></div>
        </div>
      </div>

      <div class="modal fade" tabindex="-1" role="dialog" id="signup-modal">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content"></div>
        </div>
      </div>

      <div class="modal fade" tabindex="-1" role="dialog" id="show-selected-columns">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content"></div>
        </div>
      </div>

      {% block content %}
        
        
      {% endblock  %}
      {% block scripts %}
        
      {% endblock  %}
    </body>
  </html>
{% endblock body_block %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{# <link rel="stylesheet"  href="{% static 'css/master.css'%}"> #}
{% block content %}
<style type="text/css">

	.content{
		position:absolute;
		top:40%;
		color:white;
		text-align :center;
		background-color: rgba(0,0,0,0.5)
	}



</style>

 <img src="https://thumbs.gfycat.com/AngelicThatArrowworm-size_restricted.gif" alt="Brain" style="width:100%;height:100%">
 
  <div class="content">
    <h1>If you sign up, you have the choice to add up to 10 datasets to your account for easy access when training your model</h1>
    <a style='display:inline-block; position:absolue;bottom:50%'  href="{% url 'datasets:select_dataset_for_training' %}"><h1>Start</h1></a>
  </div>
	
{% endblock  %}

templates/thanks.html
{% extends "base.html" %}


{% block content %}

<div class='jumbotron'>
	
	<h1>Thank You for Visiting. Please come back soon :) </h1>
</div>
	
{% endblock  %}

templates/welcome.html
{% extends "base.html" %}


{% block content %}

<div class='jumbotron'>
	
	<h1>Welcome {{user.username}} </h1>
</div>
	
{% endblock  %}